# This is a basic workflow to help you get started with Actions

name: Github Action Maven Build Example
on:
  push:
    branches: [ master ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name:  Step 1 checkout main branch from github
        uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Step 2 setup jdk 1.8
        uses: actions/setup-java@v1
        with:
            java-version: 1.8 

      # Runs a set of commands using the runners shell
      - name: step 3 have maven project build maven project
        run: mvn -B package --file pom.xml
        
      - name: step 4 list the current directory
        run: ls -a

      - name: step 5 what is target folder
        run: openssl genrsa -out jira_privatekey.pem 1024
        
      - name: step 5 what is target folder
        run: yes in |  openssl req -newkey rsa:1024 -x509 -key jira_privatekey.pem -out jira_publickey.cer -days 365  
        
      - name: step 5 what is target folder
        run: |
            openssl pkcs8 -topk8 -nocrypt -in jira_privatekey.pem -out jira_privatekey.pcks8
            openssl x509 -pubkey -noout -in jira_publickey.cer  > jira_publickey.pem
      - name: step 5 what is target folder
        run: dir
